### ISSUE TITLE
Notification sounds not working

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/WhatsApp-Desktop#13]
https://www.facebook.com/WhatsAppforDesktopOfficial/photos/a.517715525045288.1073741828.512479078902266/517715888378585

**Comment by borgesgabriel** [comment]
Because of [this](https://github.com/nwjs/nw.js/wiki/Using-MP3-%26-MP4-%28H.264%29-using-the--video--%26--audio--tags). Was trying to circumvent that (whilst not requiring a licence change) by implementing notification sounds natively, but it turned out to be a bit trickier than I expected because of the way you inject notifications.

**Comment by Jenianio** [comment]
Hi 

I have the same problem and i tried to understand from you conversation how to fix this problem, but unfortunately i don't understand how can it be solved. Did you able to solve it ?

Thanks

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
