### ISSUE TITLE
WhatsApp Wen Windows client does not show WhatsApp conversation, only browser update options

### ISSUE THREAD

**Issue by tlat1979** [Aluxian/WhatsApp-Desktop#53]

**Comment by wickles** [comment]
Yep I'm having this issue on both Mac and Windows version. ChitChat works fine. Maybe they changed something since the iOS web version was launched. 

![2015-08-30 13_25_02-whatsapp web](https://cloud.githubusercontent.com/assets/4229542/9569264/ae42a852-4f1a-11e5-8b82-035e240d0edc.png)

**Comment by azat-io** [comment]
@wickles Look at the previous issues. The solution coming soon, as @Aluxian said to me.

**Comment by wickles** [comment]
@azat-io thanks, didn't notice that post below.

**Comment by marty90** [comment]
gonzalocasal's solution worked for me :) (Ubuntu 14.04, 64 bit)

**Comment by wigster** [comment]
The equivalent workaround also works on Windows:
Close Whatapp-Desktop
Go to C:\User\[usrname]\Appdata\Local\UnofficialWhatsApp\ApplicationCache
Delete index
Right click on the Cache folder and change the properties to Read Only

**Comment by garenyondem** [comment]
@wigster :+1: for Windows version of solution

**Comment by tinkererguy** [comment]
I originally had it working with fresh copy of Windows 10 and no third party browsers, just Edge, then this problem came up soon afterward

So I made a slight tweak to the path suggested above, using a wildcard, to helps folks navigate to the right directory slightly easier:
C:\users\%USERNAME%\AppData\Local\UnofficialWhatsApp\Application Cache

So here's the slightly revised procedure that worked for me:
1) Close Whatapps-Desktop
2) Press **Win+R** and paste in:
C:\users\%USERNAME%\AppData\Local\UnofficialWhatsApp\Application Cache
3) Delete the file named **Index**
4) Right click on the Cache folder and change the properties to Read Only (if it's not already Read-only) 
5) Relaunch Whatsapp-Desktop, and notice Index file gets recreated, and it works again.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

Whatsie doesn't have this problem!
