### ISSUE TITLE
Crashes regularly on Ubuntu 15.10

### ISSUE THREAD

**Issue by YNedderhoff** [Aluxian/WhatsApp-Desktop#77]
"UnofficialWhatsApp crashed with SIGSEGV"

Desktop: Unity
whatsappfordesktop 1.1.0
ApportVersion: 2.19.1-0ubuntu5
Architecture: amd64

**Comment by e-M-c-E** [comment]
When is segfault then is a bigger problem. Try to run "whatsapp" from the terminal and post here entire output after the program crash.

**Comment by Aluxian** [comment]
@e-M-c-E Thanks for helping! That's how debugging is properly done.

@all, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
