### ISSUE TITLE
Not working poping up strange alert.

### ISSUE THREAD

**Issue by Kuchiriel** [Aluxian/WhatsApp-Desktop#83]
Client wont work correctly.

This pops up.

http://i.imgur.com/PHUaDde.png

Then the client ask me to select a browser.

**Comment by Aluxian** [comment]
Hey, can you please give Whatsie a try?

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

--

Just curious, what is your distro? The UI looks cool :)
