### ISSUE TITLE
Whatsapp Desktop Icon

### ISSUE THREAD

**Issue by Alister1** [Aluxian/WhatsApp-Desktop#93]
![whatsappicon](https://cloud.githubusercontent.com/assets/12628803/13535488/22b037ea-e200-11e5-9c20-4c5c75c2bd0d.png)
![whatsappicon2](https://cloud.githubusercontent.com/assets/12628803/13535489/22b16fac-e200-11e5-8363-1e2f8845d03e.png)

You can use this icons?

**Comment by Alister1** [comment]
![captura de pantalla 2016-03-04 a las 11 58 06 a m](https://cloud.githubusercontent.com/assets/12628803/13535553/715590d4-e200-11e5-9048-1e8ca655ea1d.png)
![Uploading Captura de pantalla 2016-03-04 a las 11.58.16 a.m..png…]()

**Comment by Aluxian** [comment]
That icon looks awesome! However, I think it resembles the official icon too much. Also, since WhatsApp for Desktop is now Whatsie, I have a new icon too. Check it out! :)

If you'd like to improve the current icon, feel free to do so. If I like it, I'll make it official. If you use Sketch, see my current design first: https://github.com/Aluxian/Whatsie/blob/master/design.sketch
